-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.2
-- Generation Time: Jul 06, 2021 at 04:29 AM
-- Server version: 5.7.32-35-log
-- PHP Version: 7.3.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `collinsc_recipes`
--

-- --------------------------------------------------------

--
-- Table structure for table `Recipes`
--

CREATE TABLE `Recipes` (
  `recipe_id` int(5) NOT NULL,
  `image_path` varchar(255) NOT NULL,
  `recipe_name` varchar(255) NOT NULL,
  `category` varchar(255) NOT NULL,
  `ingredients` json NOT NULL,
  `cook_time` varchar(255) NOT NULL,
  `prep_time` varchar(255) NOT NULL,
  `servings` int(3) NOT NULL,
  `author` varchar(255) NOT NULL,
  `submitted_by` varchar(255) NOT NULL,
  `oven_temp` int(4) NOT NULL,
  `instructions` json NOT NULL,
  `recipe_link` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Recipes`
--

INSERT INTO `Recipes` (`recipe_id`, `image_path`, `recipe_name`, `category`, `ingredients`, `cook_time`, `prep_time`, `servings`, `author`, `submitted_by`, `oven_temp`, `instructions`, `recipe_link`) VALUES
(3, '', 'Sour Cream Banana Bread', 'Quick Bread', '[{\"ingredient1\": \"1/2 cup of butter\", \"ingredient2\": \"1/2 cup sour cream\", \"ingredient3\": \"1 cup sugar\", \"ingredient4\": \"2 eggs\", \"ingredient5\": \"1 tsp vanilla\", \"ingredient6\": \"1 1/2 cups of flour\", \"ingredient7\": \"1 tsp baking soda\", \"ingredient8\": \"1/2 tsp of salt\", \"ingredient9\": \"1 cup mashed bananas\", \"ingredient10\": \"1/2 cup nuts (optional)\", \"ingredient11\": \"1 cup raisins (optional)\"}]', '45 - 60 min', '', 12, 'Grandma', '', 350, '[{\"one\": \"Grease and flour loaf or bundt pan with crisco\", \"six\": \"Pour the batter into your prepared pan and bake for 45 - 60 minutes at 350&deg; or until knife inserted into middle comes out clean\", \"two\": \"Cream together the butter, sugar, eggs, and vanilla.\", \"five\": \"Ruin with nuts and raisins if you really have to (don\'t feed to Sean or Skylar)\", \"four\": \"Add bananas and sour cream and mix well\", \"three\": \"Add dry ingredients and mix well.\"}]', ''),
(5, 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/delish-instantpotblackbeans-square-2-1556903633.png?crop=1xw:1xh;center,top&resize=980:*', 'Instant Pot Black Beans', 'Instant Pot', '[{\"ingredient1\": \"1lb. Dried Black Beans, Rinsed\", \"ingredient2\": \"3cups Chicken Broth\", \"ingredient3\": \"1 Onion, chunked\", \"ingredient4\": \"4 Tbsp Minced Garlic\", \"ingredient5\": \"Salt\", \"ingredient6\": \"Pepper\"}]', '1 hour', '5 min', 6, 'Makinze Gore', 'Sean Collins', 0, '[{\"instruction1\": \"To an Instant Pot add black beans, broth, onion, and garlic. Season with salt and pepper pepper pepper.\", \"instruction2\": \"Place lid on Instant Pot and set to Manual, High and set time for 35 minutes\", \"instruction3\": \"Let natural release for 15 minutes, then turn valve to quick release making sure to wait until the cycle is complete before unlocking and removing the lid. Season with more salt and pepper if desired.\"}]', 'https://www.delish.com/cooking/recipe-ideas/a27357327/instant-pot-black-beans-recipe/'),
(6, 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/ghk030119savorfeature-002-1562864329.jpg?crop=0.855xw:0.857xh;0.0901xw,0.0443xh&resize=980:*', 'Hearty Bean and Beef Chili', 'Soup', '[{\"ingredient1\": \"2tbsp. Olive Oil\", \"ingredient2\": \"1lb Ground Beef\", \"ingredient3\": \"2tsp. Ground Cumin\", \"ingredient4\": \"2tsp. Chili Powder\", \"ingredient5\": \"Salt & Pepper\", \"ingredient6\": \"1 Yellow Onion, chopped\", \"ingredient7\": \"2 Tbsp. Minced Garlic\", \"ingredient8\": \"1lb Tomatoes, Chopped\", \"ingredient9\": \"1lb Instant Pot Black Beans\"}]', '40 mins', '15', 8, 'Good Housekeeping Test Kitchen', 'Sean Collins', 0, '[{\"instruction1\": \"Heat 1 Tbsp oil in large pot on medium. Add beef, cumin, chili powder, and 1/2 tsp each salt and pepper and cook, breaking up beef, until browned, about 10 min. Transfer beef to paper towel-lined plate. \", \"instruction2\": \"Return pot to medium; add remaining Tbsp olive oil, then onion, and cook until tender, 4 to 5 min. Stir in garlic and cook 1 min. Add tomatoes and cook until they release their juices, about 5 min. Add 2 cups water and simmer until slightly thickened, about 10 min.\", \"instruction3\": \"Transfer half of beans to small bowl and mash with fork. Add to pot along with whole beans and reserved beef and heat through. \"}]', 'https://www.goodhousekeeping.com/food-recipes/easy/a28366214/hearty-bean-and-beef-chili-recipe/'),
(7, 'https://www.acouplecooks.com/wp-content/uploads/2019/03/Baked-Potato-Wedges-019.jpg', 'Baked Seasoned Potato Wedges', 'Appetizers', '[{\"ingredient1\": \"4-6 Potatoes\", \"ingredient2\": \"1/4 cup Olive Oil\", \"ingredient3\": \"2 Tsp. Salt\", \"ingredient4\": \"2 Tsp. All Seasoning Salt\", \"ingredient5\": \"1 tbsp. Balsamic Vinegar\", \"ingredient6\": \"1/2 tsp. Mustard\"}]', '40 min', '15 min', 4, 'a couple cooks', 'Sean Collins', 450, '[{\"instruction1\": \"Preheat oven to 450\", \"instruction2\": \"Wash the potatoes (do not peel). Cut the potatoes into wedges (see the video below!) and place in saucepan. Cover with about 1 inch of hot water tap water, add 1 teaspoon kosher salt and bring to a boil over high heat. Cook for 13 minutes total (the potatoes will only be boiling a few minutes). Carefully pour potatoes into strainer and allow them to sit in strainer until they stop steaming. Place potatoes in a medium bowl.\", \"instruction3\": \"Grease two baking sheets with lard or line with parchment paper\", \"instruction4\": \"In the glass liquid measuring cup, add the salted butter, 1 teaspoon kosher salt, Old Bay seasoning, and mustard powder and melt the butter in the microwave (or melt in a small saucepan on the stovetop). Stir to combine. Pour the melted butter over the potatoes in the bowl and use your hands to coat potatoes.\", \"instruction5\": \"Take the wedges out of the bowl and place them on the baking sheets, placing them as far apart as possible. Bake 20 minutes on one side, then flip the fries and bake 15 additional minutes until the wedges are crisp and golden brown, watching carefully as the cooking time can depend on the thickness and oven. (If the majority of the wedges seem soft, continue to bake a few more minutes.)\", \"instruction6\": \"Let cool for several minutes\"}]', 'https://www.acouplecooks.com/seasoned-baked-potato-wedges/'),
(8, '', 'Grandma\'s Macaroni Salad', 'Salads ', '[{\"ingredeint3\": \"dill pickles\", \"ingredient1\": \"2lbs Macoroni Noddles\", \"ingredient2\": \"Hard boiled eggs\", \"ingredient4\": \"strips of bacon\", \"ingredient5\": \"Miracle Whip to taste\", \"ingredient6\": \"Salt and Pepper to taste\"}]', '20 Minutes', '20 Minutes', 10, 'Grandma Locklar', 'Grandma Marion', 0, '[{\"ingredeint3\": \"Fry Bacon to crispy, place on paper towel to drain. Reserve bacon grease for later use.\", \"ingredient1\": \"Cook macaroni according to package directions. Drain macaroni; rinse with cold water and drain again.\", \"ingredient2\": \"Boil eggs to hard boil.\", \"ingredient4\": \"Chop eggs and pickles. Place cooked macaroni in a large bowl and add the chopped eggs and pickles.\", \"ingredient5\": \"Crumble bacon into mixture then pour a small amount of bacon grease over mixture to taste.\", \"ingredient6\": \"Add enough Miracle Whip to make creamy,add salt an pepper to taste and stir all ingredients together.\"}]', ''),
(9, '', 'Green Bean Casserole', 'Casseroles', '[{\"ingredient1\": \"6 15oz cans of green beans\", \"ingredient2\": \"3 cans cream of mushroom soup\", \"ingredient3\": \"1 cup milk\", \"ingredient4\": \"1 large package of french fried onions\"}]', '60 minutes', '10 minutes', 12, '', 'Grandma Marion', 350, '[{\"ingredient1\": \"Drain beans\", \"ingredient2\": \"Combine beans, soup, milk\", \"ingredient3\": \"Add 1/2 of the French Fried Onions to the green bean mixture; pour into a greased 9x13 inch baking dish and bake uncovered for 1 hour. Top with remaining onions and bake for 5 minutes longer\", \"ingredient4\": \"This recipe is always a special request from Azaraya. If there were nothing else on the menu Ray would be just fine with that.\"}]', ''),
(10, '', 'Apple Fritters', 'Sweet Rolls and Doughnuts', '[{\"ingredient1\": \"Vegetable oil, for deep-frying\", \"ingredient2\": \"2 cups flour\", \"ingredient3\": \"1/2 cup plus 3 Tablespoons sugar\", \"ingredient4\": \"2 1/4 teaspoons baking powder\", \"ingredient5\": \"2 teaspoons cinnamon\", \"ingredient6\": \"1 teaspoon salt\", \"ingredient7\": \"2 large eggs\", \"ingredient8\": \"3/4 cup milk\", \"ingredient9\": \"2 tablespoons melted butter\", \"ingredient10\": \"2 teaspoons vanilla extract\", \"ingredient11\": \"2 Granny Smith apples, cored and diced small\", \"ingredient12\": \"Powdered sugar, for dusting\"}]', '4-6 minutes', '35', 30, 'Ree Drummond The Pioneer Woman', 'Marion', 0, '[{\"ingredient1\": \"Heat a couple of inches of oil in a heavy pot or Dutch oven over medium-low head until a deep-fry thermometer registers 340 degrees F\", \"ingredient2\": \"In a mixing bowl, combine the flour, sugar, baking powder, cinnamon and salt. In a separate bowl, beat the eggs with a fork, then add the milk, melted butter and vanilla. Gently fold the dry and wet ingredients together until just combined (do not over-mix). Fold in the apples, adding enough to make a very chunky batter\", \"ingredient3\": \"Drop heaping tablespoons of batter into the hot oil, 6 to 8 at a time. Fry until golden brown. 4 to 6 minutes. Remove and drain on paper towels. Dust generously with powdered sugar and serve warm.\"}]', ''),
(11, 'https://img.sndimg.com/food/image/upload/c_thumb,q_80,w_566,h_318/v1/img/recipes/12/32/35/picbBMSS3.jpg', 'Soft Apple Cake', 'Cakes ', '[{\"ingredient1\": \"4 eggs\", \"ingredient2\": \"1 3/4 cup flour\", \"ingredient3\": \"1 2/3 cup sugar\", \"ingredient4\": \"1/2 cup oil\", \"ingredient5\": \"1 teaspoon baking powder\", \"ingredient6\": \"1 teaspoon salt\", \"ingredient7\": \"10 apples, peeled and sliced thin (on largest hole of a grater)\", \"ingredient8\": \"lemon juice\", \"ingredient9\": \"cinnamon\"}]', '45 minutes', '15 minutes', 18, 'Sarah Chana ', 'Marion', 350, '[{\"ingredient1\": \"Peel and slice apples\", \"ingredient2\": \"Toss apples with lemon juice so they don\'t turn brown\", \"ingredient3\": \"Beat eggs and sugar; add oil and beat until smooth\", \"ingredient4\": \"Add dry ingredients and mix well\", \"ingredient5\": \"Spray a 9x13 inch pan with cooking spray, and pour in 1/2 of the batter\", \"ingredient6\": \"Top with apples and cinnamon\", \"ingredient7\": \"Pour remaining batter on top and spread with a fork to cover apples\", \"ingredient8\": \"Bake at 350-375F for 45 minutes until light brown on top\"}]', 'https://www.food.com/recipe/my-moms-soft-apple-cake-123235'),
(12, 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2352970.jpg&w=1200&h=678&c=sc&poi=face&q=85', 'Quick and Easy Pizza Crust', 'Breads', '[{\"ingredient1\": \"1 (.25 ounce) package active dry yeast\", \"ingredient2\": \"1 teaspoon sugar\", \"ingredient3\": \"1 cup warm water \", \"ingredient4\": \"2 1/2 cups flour\", \"ingredient5\": \"2 tablespoons olive oil\", \"ingredient6\": \"1 teaspoon salt\"}]', '15-20 minutes', '10 minutes', 8, 'Chef Rider', 'Marion', 450, '[{\"ingredient1\": \"Preheat oven to 450 degrees F (230 degrees C). In a medium bowl, dissolve yeast and sugar in warm water. Let stand until creamy, about 10 minutes.\", \"ingredient2\": \"Stir in flour, salt and oil. Beat until smooth. Let rest for 5 minutes.\", \"ingredient3\": \"Turn dough out onto a lightly floured surface and pat or roll into a round. Transfer crust to a lightly greased pizza pan or baker\'s peel dusted with cornmeal. Spread with desired toppings and bake in preheated oven for 15 to 20 minutes, or until golden brown. Let baked pizza cool for 5 minutes before serving.\"}]', 'https://www.allrecipes.com/recipe/20171/quick-and-easy-pizza-crust/?internalSource=hub%20recipe&referringContentType=Search'),
(13, 'https://img.sndimg.com/food/image/upload/c_thumb,q_80,w_621,h_350/v1/img/recipes/30/23/74/picH9kfA0.jpg', 'Honey Baked Rabbit or Chicken ', 'Wild Game', '[{\"ingredient1\": \"1 Whole rabbit or 1-1 1/2 lb chicken, cut up\", \"ingredient2\": \"1/3 cup butter\", \"ingredient3\": \"1/3 cup honey\", \"ingredient4\": \"1 teaspoon salt\", \"ingredient5\": \"1 teaspoon pepper\", \"ingredient6\": \"1 teaspoon curry powder\"}]', '1 hour 15 minutes', '10', 4, 'Food.com', 'Marion ', 350, '[{\"ingredient1\": \"Arrange meat in a shallow baking dish\", \"ingredient2\": \"Mix together all other ingredients\", \"ingredient3\": \"Pour mixture over meat\", \"ingredient4\": \"Bake at 350F for 1-1.5 hours basting frequently while cooking.\"}]', 'https://www.food.com/recipe/honey-baked-rabbit-or-chicken-302374'),
(14, 'https://happymoneysaver.com/wp-content/uploads/2018/10/easy-freezer-meals-1-1-768x1151.jpg', 'Cube Steaks with Gravy', 'No Cook-Prep, Instant Pot Meal', '[{\"ingredient1\": \"6 cube steaks\", \"ingredient2\": \"2 cups water\", \"ingredient3\": \"1 cup pureed or diced onion\", \"ingredient4\": \"1/2 cup soy or tamari sauce\", \"ingredient5\": \"2 Tablespoons Worchestershire sauce\", \"ingredient6\": \"2 tsp minced garlic\", \"ingredient7\": \"2 Tablespoons beef bouillon\", \"ingredient8\": \"Salt and pepper\"}]', '25-30 minutes', '10 minutes', 6, 'From: HappyMoneySaver.com', 'Marion', 0, '[{\"ingredient1\": \"MAKE IT NOW: Add all ingredients in an Instant Pot. Cook for 20 minutes at high pressure, then do quick release. Place on saute. Remove steaks. Whisk in a small bowl 1/4 cup cornstarch with 1/2 cup water until smooth. Pour mixture into the liquids left in the Instant Pot. Whisk continually until gravy starts to thicken. Add cube steaks back into the pot, heat until warmed through and serve.\", \"ingredient2\": \"MAKE IT A FREEZER MEAL: Add all ingredients to a gallon sized freezer bag or container. Remove as much air as possible and place in freezer.\", \"ingredient3\": \"COOK FROM FROZEN: Add contents into an instant pot. Add 1/4 cup water. Cook for 23 minutes at high pressure, then do a quick release. Place on saute. Remove steaks. Whisk in a small bowl 1/4 cup cornstarch with 1/2 cup water until smooth. Pour mixture into the liquids left in the Instant Pot. Whisk continually until gravy starts to thicken. Add cube steaks back into the pot, heat until warmed through and serve.\", \"ingredient3 (copy)\": \"COOK FROM FROZEN: Add contents into an instant pot. Add 1/4 cup water. Cook for 23 minutes at high pressure, then do a quick release. Place on saute. Remove steaks. Whisk in a small bowl 1/4 cup cornstarch with 1/2 cup water until smooth. Pour mixture into the liquids left in the Instant Pot. Whisk continually until gravy starts to thicken. Add cube steaks back into the pot, heat until warmed through and serve.\"}]', 'https://happymoneysaver.com/easy-freezer-meals/'),
(15, 'https://happymoneysaver.com/wp-content/uploads/2014/11/Sausage-Gumbo5Best1-681x1024.jpg', 'Easy Sausage Gumbo', 'Instant Pot Freezer Meals', '[{\"ingredient1\": \"12 oz Smoked turkey or Kielbasa sausage, sliced\", \"ingredient2\": \"10 oz okra, fresh or frozen. *I leave this out*\", \"ingredient3\": \"1 medium onion, chopped\", \"ingredient4\": \"1 red bell pepper, chopped\", \"ingredient5\": \"2 teaspoons minced garlic\", \"ingredient6\": \"28 oz can of diced tomatoes, with juices\", \"ingredient7\": \"1 Tablespoon worcestershire sauce\", \"ingredient8\": \"1/4 teaspoon salt\", \"ingredient9\": \"1/4 teaspoon pepper\", \"ingredient10\": \"2 dashes tabasco or hot sauce. Note: Creole seasoning can also be added to give a little more spice. \"}]', '20 minutes', '20 minutes', 6, 'www.happymoneysaver.com', 'Marion', 0, '[{\"ingredient1\": \"MAKE IT NOW: Place all ingredients in the instant pot. Cook for 9 minutes at high pressure, then allow 10 minutes for natural release.\", \"ingredient2\": \"MAKE IT A FREEZE MEAL: Place all ingredients in a gallon size freezer bag, remove as much air as possible. Place in freezer.\", \"ingredient3\": \"COOK FROM FROZEN: Add contents into an instant pot. Add 1/4 cup water. Cook for 10 minutes at high pressure then allow 10 minutes for natural release.\", \"ingredient4\": \"Serve with rice\"}]', 'https://happymoneysaver.com/easy-crock-pot-sausage-gumbo-2/'),
(16, 'https://happymoneysaver.com/wp-content/uploads/2010/09/beefstew1.gif', 'Beef Barley Stew', 'Instant Pot Freezer Meals', '[{\"ingredient1\": \"1 lb beef stew meat, diced\", \"ingredient2\": \"1-1/4 cups diced carrot, fresh or frozen\", \"ingredient3\": \"1 onion, diced or pureed\", \"ingredient4\": \"3 ribs celery, diced\", \"ingredient5\": \"1 15oz can tomato sauce\", \"ingredient6\": \"1/2 cup pearl barley\", \"ingredient7\": \"5 cups water\", \"ingredient8\": \"1 teaspoon parsley flakes\", \"ingredient9\": \"1/4 teaspoon pepper\", \"ingredient10\": \"1 teaspoon sugar\", \"ingredient11\": \"2 Tablespoons Beef Bouillon powder\"}]', '30', '30', 6, 'Happymoneysaver.com', 'Marion', 0, '[{\"ingredient1\": \"Add all ingredients to a gallon sized freezer bag \", \"ingredient2\": \"MAKE IT NOW: transfer all ingedients to the instant pot. Cook for 27 minutes at high pressure, then allow 10 minutes for natural release\", \"ingredient3\": \"MAKE IT FROM FROZEN: transfer all ingedients to the instant pot. Add 1/4 cup water. Cook for 30 minutes at high pressure, then allow 10 minutes for natural release\"}]', 'https://happymoneysaver.com/easy-freezer-meals/'),
(17, 'https://bubbapie.com/wp-content/uploads/2019/11/Macaroni-and-Corn-Casserole-683x1024.jpg', 'Corn and Macaroni Casserole', 'Casseroles', '[{\"ingredient1\": \"1 can creamed corn\", \"ingredient2\": \"1 can corn (undrained)\", \"ingredient3\": \"1 cup macaroni (uncooked)\", \"ingredient4\": \"1 stick of butter\", \"ingredient5\": \"8oz Velveeta cheese\"}]', '1 Hour', '10 minutes', 12, 'bubbapie.com', 'Marion', 350, '[{\"ingredient1\": \"Butter a 9x13 baking dish; in the baking dish:\", \"ingredient2\": \"Mix together corns, macaroni,and cheese.\", \"ingredient3\": \"Slice butter, and mix into corn mixture\", \"ingredient4\": \"Cover and place in 350F oven, Bake covered for 30 minutes. Uncover,stir, and bake for 30 additional minutes.\"}]', 'https://bubbapie.com/easy-macaroni-corn-casserole/'),
(18, 'https://s23209.pcdn.co/wp-content/uploads/2013/10/Loaded-Baked-Potato-Soup.jpg', 'Loaded Potato Soup', 'Soups', '[{\"ingredient1\": \"4 slices of bacon, diced\", \"ingredient2\": \"5 Tablespoons butter\", \"ingredient3\": \"1/4 cup flour\", \"ingredient4\": \"3 1/2 cups milk (I usually substitute 1-1 1/2 cups heavy whipping cream for part of the milk)\", \"ingredient5\": \"3 potatoes peeled and cubed \", \"ingredient6\": \"2 green onions thinly sliced\", \"ingredient7\": \"1 cup shredded cheddar cheese\", \"ingredient8\": \"1/2 cup sour cream\", \"ingredient9\": \"salt and pepper to taste\"}]', '30 minutes', '10', 4, 'damndelicious.com', 'Marion', 0, '[{\"ingredient1\": \"Heat a large skillet over medium high heat. Add bacon and cook until brown and crispy, about 6-8 minutes. Transfer to a paper towel-lined plate; set aside.\", \"ingredient2\": \"Melt butter in a large stockpot or Dutch oven over medium heat. Whisk in flour until lightly browned, about 1 minute. Gradually whisk in milk, and cook, whisking constantly, until slightly thickened, about 1-2 minutes. Stir in potatoes and green onions.\", \"ingredient3\": \"Bring to a boil; reduce heat and simmer until potatoes are tender, about 15-20 minutes. Stir in cheese, sour cream, salt and pepper, to taste. If the soup is too thick, add more milk as needed until desired consistency is reached.\", \"ingredient4\": \"Serve immediately, garnish with green onion, cheese, and bacon if desired \"}]', 'https://damndelicious.net/2013/10/14/loaded-baked-potato-soup/'),
(19, 'https://www.plainchicken.com/wp-content/uploads/2020/03/IMG_3262.JPG', 'Crack Potatoes', 'Casseroles', '[{\"ingredient1\": \"2 16oz containers sour cream\", \"ingredient2\": \"2 cups cheddar cheese, shredded\", \"ingredient3\": \"2 3oz bags real bacon bits\", \"ingredient4\": \"2 packages Ranch Dip mix\", \"ingredient5\": \"1 large bag of frozen hash brown potatoes\"}]', '45 minutes', '10 minutes', 10, 'Stephanie@plainchicken', 'Marion', 400, '[{\"ingredient1\": \"Combine first 4 ingredients, mix in hash browns and spread evenly in a 9x13 greased baking pan. Bake at 400F for 45-60 minutes.\"}]', 'https://www.plainchicken.com/crack-potatoes/'),
(20, 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F631314.jpg&w=595&h=595&c=sc&poi=face&q=85', 'Soft Chocolate Chip Cookies', 'Cookies', '[{\"ingredient1\": \"4 1/2 cups flour\", \"ingredient2\": \"2 teaspoons baking soda\", \"ingredient3\": \"2 cups butter, softened\", \"ingredient4\": \"1 1/2 cups packed brown sugar\", \"ingredient5\": \"1/2 cup white sugar\", \"ingredient6\": \"2 (3.4oz) packages instant vanilla pudding mix (I use the french vanilla)\", \"ingredient7\": \"4 eggs\", \"ingredient8\": \"2 teaspoons vanilla extract\", \"ingredient9\": \"4 cups semisweet chocolate chips\", \"ingredient10\": \"2 cups chopped walnuts (optional)\"}]', '10-12 minutes', '15 minutes', 72, 'Allrecipes.com', 'Marion', 350, '[{\"ingredient1\": \"Preheat oven to 350F. Sift together flour and baking soda, set aside.\", \"ingredient2\": \"In a large mixing bowl, cream together the butter and sugars. Beat in the instant pudding mix until blended. Stir in the eggs and vanilla. Blend in the flour mixture.Finally, stir in the chocolate chips and nuts. Drop by rounded spoonfuls onto ungreased cookie sheets.\", \"ingredient3\": \"Bake 10 to 12 minutes until edges are golden brown.\"}]', 'https://www.allrecipes.com/recipe/15004/award-winning-soft-chocolate-chip-cookies/'),
(21, 'https://storcpdkenticomedia.blob.core.windows.net/media/recipemanagementsystem/media/recipe-media-files/recipes/retail/x17/19869-sour-cream-cornbread-600x600.jpg?ext=.jpg', 'Sour Cream Cornbread', 'Breads', '[{\"ingredient1\": \"1/4 cup butter\", \"ingredient2\": \"3 Tablespoons sugar, (I use 1/2 cup)\", \"ingredient3\": \"2 eggs\", \"ingredient4\": \"1/2 cup sour cream\", \"ingredient5\": \"1/2 cup milk\", \"ingredient6\": \"1 cup flour\", \"ingredient7\": \"2/3 cup yellow cornmeal\", \"ingredient8\": \"1 1/2 teaspoon baking powder\", \"ingredient9\": \"1/2 teaspoon salt\", \"ingredient10\": \"1/4 teaspoon baking soda\"}]', '25-30 minutes', '10', 9, 'landoflakes.com', 'Marion', 425, '[{\"ingredient1\": \"Heat oven to 425F.\", \"ingredient2\": \"Combine butter and sugar; beat at medium speed until creamy.\", \"ingredient3\": \"Add eggs beating well\", \"ingredient4\": \"Stir in sour cream and milk\", \"ingredient5\": \"Add all remaining ingredients.\", \"ingredient6\": \"Beat on low just until blended (I usually stir just until blended).\", \"ingredient7\": \"Pour batter into greased 8x8 pan; bake for 25-30 minutes, or until knife inserted comes out clean.\", \"ingredient8\": \"I typically double this recipe and bake in a 9x13 inch pan which will increase cook time.\"}]', 'https://www.landolakes.com/recipe/19869/sour-cream-cornbread/'),
(40, 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F194018.jpg&w=596&h=596&c=sc&poi=face&q=85', 'Frog-Eyed Salad (Acini De Pepe Fruit Salad)', 'Salad', '[{\"ingredient0\": \"1/2 of a (1-pound) package Acini De Pepe, uncooked\", \"ingredient1\": \"1 egg\", \"ingredient2\": \"1/2 cup sugar\", \"ingredient3\": \"1 tbsp. flour\", \"ingredient4\": \"1/4 tsp. salt\", \"ingredient5\": \"1 (15 1/4 ounce) can juice-pack crushed pineapple, drained, reserving juice\", \"ingredient6\": \"1 (16 ounce) can fruit cocktail, drained\", \"ingredient7\": \"1 cup miniature marshmallows\", \"ingredient8\": \"1 cup (1/2 pint) whipping cream\"}]', '--', '1 hour 15 minutes', 6, 'Grandma', 'Grandma', 0, '[{\"ingredient0\": \"Prepare Acini De Pepe according to package instructions.\", \"ingredient1\": \"In heavy saucepan, beat eggs with a wire whisk until foamy\", \"ingredient2\": \"Stir in sugar, flour, salt and reserved pineapple liquid\", \"ingredient3\": \"Over low heat, cook and stir mixture until thick and bubbly\", \"ingredient4\": \"In a large bowl combine the Acini De Pepe with egg mixture\", \"ingredient5\": \"Chill thoroughly for 1 hour\", \"ingredient6\": \"Stir in pineapple, fruit cocktail and marshmallows, fold in whipped cream\", \"ingredient7\": \"Cover, chill thoroughly and stir before serving.  Refrigerate leftovers.\"}]', ''),
(41, 'https://amandascookin.com/wp-content/uploads/2021/04/Strawberry-Jello-Pretzel-Salad-RC-500x500.jpg', 'Pretzel Salad', 'Salad', '[{\"ingredient0\": \"2 cup crushed pretzels\", \"ingredient1\": \"3/4 cup melted butter\", \"ingredient2\": \"4 Tablespoons sugar\", \"ingredient3\": \"8 ounce package cream cheese\", \"ingredient4\": \"1 cup confectioners sugar\", \"ingredient5\": \"1 large carton cool whip\", \"ingredient6\": \"2 cups boiling water\", \"ingredient7\": \"1 large package strawberry jello\", \"ingredient8\": \"2 10 oz. packages frozen strawberries\"}]', '6 minutes', '30 minutes', 0, '', 'Grandma', 400, '[{\"ingredient0\": \"Mixed crushed pretzels, butter, and sugar. \", \"ingredient1\": \"Spread on the bottom of 9x13 inch pan\", \"ingredient2\": \"Bake for 6 minutes at 400 degrees. Let cool .\", \"ingredient3\": \"Mix cream cheese, confectioners sugar and cool whip and spread over crust.\", \"ingredient4\": \"Dissolve Jello in water and mix in frozen strawberries, stir often, when almost set pour over cream cheese layer and chill\"}]', ''),
(42, '', 'Test', '', '[{\"ingredient0\": \"\"}]', '', '', 0, '', '', 0, '[{\"ingredient0\": \"\"}]', ''),
(43, '', 'Test', '', '[{\"ingredient0\": \"\"}]', '', '', 0, '', '', 0, '[{\"ingredient0\": \"\"}]', ''),
(44, '', 'Test', '', '[{\"ingredient0\": \"\"}]', '', '', 0, '', '', 0, '[{\"ingredient0\": \"\"}]', ''),
(45, '', 'Test', '', '[{\"ingredient0\": \"\"}]', '', '', 0, '', '', 0, '[{\"ingredient0\": \"\"}]', ''),
(46, '', 'test', '', '[{\"ingredient0\": \"\"}]', '', '', 0, '', '', 0, '[{\"ingredient0\": \"\"}]', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `Recipes`
--
ALTER TABLE `Recipes`
  ADD UNIQUE KEY `recipe_id` (`recipe_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `Recipes`
--
ALTER TABLE `Recipes`
  MODIFY `recipe_id` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=47;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
